namespace Constant {
    public enum GachaChestProductId {
        Gold = 0,
        BombRainbow = 1,
        BombCoolPuffy = 2,
        TrailRainbow = 3,
        AngelWing = 4,
        AngelCape = 5,
        DevilWing = 6,
        BombCandyBall = 7,

        // Poo = 8,
        Knight = 9,
        Man = 10,

        // Vampire = 11,
        Witch = 12,

        // Doge = 13,
        // Pepe = 14,
        Ninja = 15,

        // King = 16,
        // Rabbit = 17,
        Key = 18,
        Shield = 19,
        RankGuardian = 20,
        FullRankGuardian = 21,
        ConquestCard = 22,
        FullConquestCard = 23,
        Loudspeaker = 24,
        BombStarBeam = 25,
        BombAdd1 = 26,
        SpeedAdd1 = 27,
        RangeAdd1 = 28,
        Unknown = -1,

        // Use in Reward LuckyWheel and Daily Gilt
        RewardGem = 102,
        RewardGemLock = 103,
        RewardGold = 104,
        RewardCoin = 105,

        // Add new Hero sprint 5
        MrPoo = 8,
        GKu = 11,
        PinkyToon = 13,
        Stickman = 14,
        Monitor = 16,
        Dragon = 17,
        Santa = 100,
        Miner,

        // Add new Bomb sprint 5
        BombPufferFish = 37,
        BombDogeCoin = 38,
        BombWukong = 39,
        BombPepe = 40,
        BombPilotRabbit = 41,
        BombSnowman = 42,
        BombThunder = 43,
        BombWatermelon = 44,
        BombWitchPurple = 45,
        BombBlackCat = 46,
        BombTiger = 47,
        BombPugDog = 48,
        BombMonitor = 49,
        BombMrPoo = 50,
        BombDragoon = 51,
        BombPinkytoon = 52,
        BombGBPink = 53,
        BombGoldMiner = 54,
        BombStickman = 55,
        BombDragon = 56,
        BombSantaClaus = 57,
        BombPumpkin = 58,
        BombWerewolves = 59,
        BombGhost = 60,

        // Add new Wing sprint 5
        WingValkyrie = 61,
        WingSavior = 62,
        WingGearX = 63,
        WingAsura = 64,
        WingMoonblader = 65,
        WingTrigrams = 66,
        WingRainbow = 67,
        WingLucifer = 68,
        WingYamato = 69,
        WingVenom = 70,
        WingShuriken = 71,
        WingShurikenOri = 72,
        WingMijonir = 73,
        WingCasperAngel = 74,

        // Add new Fire sprint 5
        FireDoge = 75,
        FireWukong = 76,
        FirePepe = 77,
        FireRabbit = 78,
        FireWater = 79,
        FireSnow = 80,
        FireStarBeam = 81,
        FireThunder = 82,
        FireMelon = 83,
        FirePurple = 84,
        FireTiger = 85,
        FireDarkCat = 86,
        FireDogBite = 87,
        FireMornitor = 88,
        FireGreenStar = 89,
        FireBlackMagic = 90,
        FirePinkyToon = 91,
        FirePinkForce = 92,
        FireMiner = 93,
        FireSword = 94,
        FireDragonBurn = 95,
        FireCandy = 96,
        FirePumpkin = 97,
        FireCrawWolf = 98,
        FireGhost = 99,
        MysteryBox = 106,
        Scrap = 107,
        LesserCrystal = 108,
        RoughCrystal = 109,
        PureCrystal = 110,
        PerfectCrystal = 111,

        // Add new Heroes, Bomb, Fire sprint 6 (Tet holiday)
        BombFireWork = 112,
        BombApricot = 113,
        FireFireWork = 114,
        FireApricot = 115,
        Calico = 116,
        Kuroneko = 117,
        GoldenKat = 118,
        MrDear = 119,
        TLion = 120,
        BombGreenMelon = 121,
        WingPhoenix = 122,
        FireGreenMelon = 123,

        // Add new Trail, sprint 9
        TrailMultiShadow = 124,
        TrailHappyColor = 125,
        TrailNitro = 126,

        // Add new Skin, sprint 9
        HeroFrog = 127,
        HeroDoge = 128,
        HeroKing = 129,
        HeroCupid = 130,
        HeroBGuy = 131,

        // Emoji, print 10
        EmojiSmirk = 132,
        EmojiAngry = 133,
        EmojiSad = 134,
        EmojiHappy = 135,
        
        //Add new Skin, sprint 10
        HeroPinkyBear = 136,
        
        //Add new Skin, sprint 12
        BombSakura = 137,
        FireSakuraBloom = 138,
        TrailSakuraPetal = 139,
        TrailRedHeart = 140,
        HeroPinkyNeko = 141,
        TrailSkySpark = 142,
        
        HeroDragoon = 143,
        HeroFatTiger = 144,
        HeroHesman = 145,
        
        EmojiBCOIN = 152,
        EmojiSEN = 153,
        EmojiDoge = 154,
        EmojiDogeBonk = 155,
        EmojiPepeCry = 156,
        EmojiPepeShock = 157,
        
        //Add new Avatar
        AvatarNinjaFury = 146,
        AvatarJoyfulSpell = 147,
        AvatarMightyFist = 148,
        AvatarRedHot = 149,
        AvatarFinalForm = 150,
        AvatarReckoning = 151,
    }
}